# Generated by Django 4.2 on 2023-05-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('url', models.CharField(default=None, max_length=250)),
                ('img', models.ImageField(default=None, upload_to='images/')),
            ],
        ),
    ]
